import { createHash, createPublicKey } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { JwkSet } from '@modules/oauth/token/interfaces/jwks.interface';

/** The only algorithm this server signs or publishes. */
export const SIGNING_ALGORITHM = 'RS256';

/**
 * Where the key pair lives, resolved from the working directory.
 *
 * It sits outside `src/` because the PEMs are a deployment artifact, not
 * source: gitignored, mounted by Docker, generated by `npm run
 * generate-signing-keys`. Being relative to `process.cwd()` means the server
 * has to be started from the project root — `WORKDIR /app` guarantees that
 * in the image.
 */
const SECRETS_DIR = join(process.cwd(), 'secrets');

let privateKeyPem: string | undefined;
let publicKeyPem: string | undefined;
let signingKeyId: string | undefined;
let publicJwks: JwkSet | undefined;

/**
 * The private signing key — **the only place it is read**.
 *
 * Cached after the first call: the file never changes while the process
 * lives, and re-reading it on every token would put the key through the
 * filesystem hundreds of times a minute for nothing.
 *
 * @returns The PEM text, to hand straight to the signer.
 * @throws If `secrets/private.pem` does not exist.
 */
export function getPrivateKeyPem(): string {
  privateKeyPem ??= readFileSync(join(SECRETS_DIR, 'private.pem'), 'utf8');
  return privateKeyPem;
}

/**
 * The public half, read from its own file and cached the same way.
 *
 * Deriving it from the private key would work and is deliberately not done:
 * everything published comes from `public.pem` alone, so no private member
 * can reach the JWK Set by accident.
 *
 * @returns The PEM text.
 * @throws If `secrets/public.pem` does not exist.
 */
export function getPublicKeyPem(): string {
  publicKeyPem ??= readFileSync(join(SECRETS_DIR, 'public.pem'), 'utf8');
  return publicKeyPem;
}

/**
 * The `kid` every token carries, and every published key is filed under.
 *
 * It is the key's RFC 7638 thumbprint: SHA-256 over the canonical JWK
 * members — `e`, `kty`, `n`, in that order, with no whitespace — so the same
 * key always yields the same id, and a different key never does. A random id
 * would work until the key was regenerated somewhere else.
 *
 * @returns The thumbprint, base64url-encoded.
 * @throws If `secrets/public.pem` does not exist or is not a valid RSA key.
 */
export function getSigningKeyId(): string {
  if (!signingKeyId) {
    const { e, kty, n } = createPublicKey(getPublicKeyPem()).export({
      format: 'jwk',
    });
    signingKeyId = createHash('sha256')
      .update(JSON.stringify({ e, kty, n }))
      .digest('base64url');
  }
  return signingKeyId;
}

/**
 * The JWK Set `GET /oauth/jwks` serves (RFC 7517).
 *
 * **Derived from `public.pem` only** — never from the private key — so there
 * is no path by which `d`, `p` or `q` could be exported into a public
 * response. Each key carries its `kid`, `alg` and `use: 'sig'` so a verifier
 * can select it without guessing.
 *
 * @returns The set, cached after the first call.
 * @throws If `secrets/public.pem` does not exist or is not a valid RSA key.
 */
export function getPublicJwks(): JwkSet {
  publicJwks ??= {
    keys: [
      {
        ...createPublicKey(getPublicKeyPem()).export({ format: 'jwk' }),
        kid: getSigningKeyId(),
        alg: SIGNING_ALGORITHM,
        use: 'sig',
      },
    ],
  };
  return publicJwks;
}
