export const ENV = {
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  MONGO_DATABASE: 'MONGO_DATABASE',
  AUTH_FRONT_URL: 'AUTH_FRONT_URL',
  ADMIN_API_KEY: 'ADMIN_API_KEY',
  OIDC_ISSUER: 'OIDC_ISSUER',
} as const;
