export const ENV = {
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  MONGO_DATABASE: 'MONGO_DATABASE',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  ADMIN_API_KEY: 'ADMIN_API_KEY',
  OIDC_ISSUER: 'OIDC_ISSUER',
} as const;
