export const ENV = {
  PORT: 'PORT',
  MONGO_URI: 'MONGO_URI',
  MONGO_DATABASE: 'MONGO_DATABASE',
  ADMIN_API_KEY: 'ADMIN_API_KEY',
  OIDC_ISSUER: 'OIDC_ISSUER',

  LOGIN_APP_URL: 'LOGIN_APP_URL',
  CORS_ORIGINS: 'CORS_ORIGINS',
  COOKIE_SECURE: 'COOKIE_SECURE',
} as const;
